# Generated by Django 2.0.6 on 2018-07-04 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-publish_time']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='blog',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
