# Generated by Django 2.0.6 on 2018-07-06 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180705_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='SublimtMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('publish_time', models.DateTimeField(default=datetime.datetime.now)),
                ('is_show', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-publish_time'],
            },
        ),
    ]
